[project]
name = "pycaffe"
version = "0.0.1"
description = "Caffe: a fast open framework for deep learning."
authors = [
    {name = "xinetzone", email = "735613050@qq.com"},
]
requires-python = ">=3.10"
readme = "README.md"
maintainers = [
  {name = "xinetzone", email = "735613050@qq.com"},
]
keywords = ['daobook', 'caffe']
classifiers = [
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent", 
]
dependencies = [
  "numpy",
  "scipy",
  "scikit-image",
  "protobuf",
  "six"
]

[build-system]
requires = ["setuptools", "wheel", "conan", "oldest-supported-numpy", "ninja"]

[tool.cibuildwheel]
build = ["cp312-*"]
manylinux-x86_64-image = "quay.io/pypa/manylinux_2_28_x86_64"
test-requires = ["pytest", "pydot", "numpy"]
test-command = [
  "pytest {project}/python/caffe/test"
]
xbuild-tools = ["cmake>=3.23.0", "ninja"]

[tool.cibuildwheel.windows]
archs = ["AMD64"]
before-all = [
  "choco install graphviz"
]

[tool.cibuildwheel.linux]
archs = ["x86_64"]
before-all = [
  "yum update",
  "yum install graphviz -y",
  "pip install conan",
  "conan remote add conancenter https://center2.conan.io --force",
  "conan profile detect --force",
  "echo 'compiler.libcxx=libstdc++11' >> ~/.conan2/profiles/default"
]
[tool.cibuildwheel.macos]
archs = ["x86_64"]
before-all = [
  "brew install graphviz"
]

[tool.cibuildwheel.macos.environment]
